### ISSUE TITLE
OpenGL on Linux fails

### ISSUE THREAD

**Issue by philstopford** [philstopford/Variance_GPL#1]
e.g.

```
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.InvalidCastException: Unable to cast object of type 'OpenTK.Platform.X11.X11WindowInfo' to type 'OpenTK.Platform.Linux.LinuxWindowInfo'.
   at OpenTK.Platform.Linux.LinuxFactory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at Eto.Veldrid.VeldridSurface.OnWindowInfoUpdated(EventArgs e) in D:\development\git\DesignLibs_GPL\Eto\Eto.VeldridSurface\VeldridSurface.cs:line 264
   at Eto.Veldrid.VeldridSurface.Callback.OnWindowInfoUpdated(VeldridSurface s, EventArgs e) in D:\development\git\DesignLibs_GPL\Eto\Eto.VeldridSurface\VeldridSurface.cs:line 48
   at Eto.Veldrid.Gtk.GtkVeldridSurfaceHandler.<.ctor>b__10_0(Object sender, EventArgs e) in D:\development\git\DesignLibs_GPL\Eto\Eto.Veldrid.Gtk\GtkVeldridSurfaceHandler.cs:line 34
   at Eto.Veldrid.Gtk.GtkVeldridDrawingArea.UpdateWindowInfo(GraphicsMode mode) in D:\development\git\DesignLibs_GPL\Eto\Eto.Veldrid.Gtk\GtkVeldridDrawingArea.cs:line 56
   at Eto.Veldrid.Gtk.GtkVeldridSurfaceHandler.UpdateWindowInfo(GraphicsMode mode) in D:\development\git\DesignLibs_GPL\Eto\Eto.Veldrid.Gtk\GtkVeldridSurfaceHandler.cs:line 75
   at Eto.Veldrid.VeldridSurface.InitializeGraphicsBackend() in D:\development\git\DesignLibs_GPL\Eto\Eto.VeldridSurface\VeldridSurface.cs:line 201
   at Eto.Veldrid.VeldridSurface.Callback.InitializeGraphicsBackend(VeldridSurface s) in D:\development\git\DesignLibs_GPL\Eto\Eto.VeldridSurface\VeldridSurface.cs:line 44
   at Eto.Veldrid.Gtk.GtkVeldridSurfaceHandler.Control_Drawn(Object o, DrawnArgs args) in D:\development\git\DesignLibs_GPL\Eto\Eto.Veldrid.Gtk\GtkVeldridSurfaceHandler.cs:line 86
   at Gtk.Widget.DrawnSignalCallback(IntPtr inst, IntPtr arg0, IntPtr gch)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at Gtk.Widget.DrawnSignalCallback(IntPtr inst, IntPtr arg0, IntPtr gch)
   at Gtk.Application.Run()
   at Eto.GtkSharp.Forms.ApplicationHandler.Run()
   at Variance.Gtk.MainClass.Main(String[] args) in D:\development\git\Variance_GPL\Eto\Variance.Gtk\Program.cs:line 16

```

**Comment by philstopford** [comment]
Upstream Eto.Veldrid project has been working on this; merged changes into DesignLibs version and this will resolve the problem above.
